<?php

/**
 * @file
 * General functions and hook implementations.
 *
 * @see https://harvesthq.github.com/chosen/
 */

/**
 * Implements hook_library_info_alter().
 */
function vanilla_selectbox_lib_library_info_alter(array &$libraries, $module) {
  if ('vanilla_selectbox_lib' == $module) {
    if (isset($libraries['chosen'])) {
      // Set chosen library path.
      $vanilla_selectbox_js_path = _vanilla_selectbox_lib_get_vanilla_selectbox_path();
      $minified = file_exists($vanilla_selectbox_js_path . '/chosen.jquery.min.js');
      $vanilla_selectbox_js_path = '/' . $vanilla_selectbox_js_path;
      $vanilla_selectbox_js = $minified
        ? $vanilla_selectbox_js_path . '/chosen.jquery.min.js'
        : $vanilla_selectbox_js_path . '/chosen.jquery.js';
      $libraries['chosen']['js'][$vanilla_selectbox_js] = [
        'minified' => $minified,
      ];
      $vanilla_selectbox_css = $vanilla_selectbox_js_path . '/chosen.css';
      $libraries['chosen.css']['css']['component'][$vanilla_selectbox_css] = [];
    }
  }
}

/**
 * Get the location of the chosen library.
 *
 * @return string
 *   The location of the library, or FALSE if the library isn't installed.
 */
function _vanilla_selectbox_lib_get_vanilla_selectbox_path() {
  if (function_exists('libraries_get_path')) {
    return libraries_get_path('chosen');
  }

  // The following logic is taken from libraries_get_libraries()
  $searchdir = [];

  // Similar to 'modules' and 'themes' directories inside an installation
  // profile, installation profiles may want to place libraries into a
  // 'libraries' directory.
  $searchdir[] = 'profiles/' . \Drupal::installProfile() . '/libraries';

  // Always search libraries.
  $searchdir[] = 'libraries';

  // Also search sites/<domain>/*.
  $searchdir[] = \Drupal::service('site.path') . '/libraries';

  foreach ($searchdir as $dir) {
    if (file_exists($dir . '/chosen/chosen.jquery.min.js') || file_exists($dir . '/chosen/chosen.jquery.js')) {
      return $dir . '/chosen';
    }
  }

  return FALSE;
}
